sudo: required
services:
  - docker
  before_install:
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
    # Set up google cloud locally
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    # Install kubectl
    - gcloud components update kubectl
    # Auth in gcloud / Similiar to IAM an security group key configuration
    - gcloud auth activate-service-account --key-file service-account.json
