apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      label:
        component: web
    spec:
      - name: client
        image: ickyblindman/complex-client
        ports:
          - containerPort: 3000
